version: 1

info:
  id: otaviojava-payara-nosql
  name: Helidon
  description: |
    <p>Helidon is a collection of Java libraries for writing microservices that run on a fast web core powered by Netty.</p>
  tags:
    - Java
    - MicroProfile
    - Maven
  notes:
    - heading: "Features"
      content: |
        Java 11<br />
        MongoDB<br />
        Automatic TLS certificates<br />
        Maven-based build<br />

initialize:
  repository: git://github.com/otaviojava/payara-nosql.git@master
  config: null
  files: []
  profile: MicroProfile