version: 1

info:
  id: otaviojava-payara-nosql
  name: Payara NoSQL
  description: |
    <p>Payara NoSQL Sample with Java 11.</p>
  tags:
    - Java
    - MicroProfile
    - Maven
  notes:
    - heading: "Features"
      content: |
        Java 11<br />
        MongoDB<br />
        Automatic TLS certificates<br />
        Maven-based build<br />

initialize:
  repository: git://github.com/otaviojava/payara-nosql.git@master
  config: null
  files: []
  profile: MicroProfile
